###Her bliver alle de ord vi vil lave om, lavet om####
####Simple reduktioner####
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<åbner\\>|\\åbnet\\>)", replacement = "åbnes")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<abstrakte\\>)", replacement = "abstrakt")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<naturfagene\\>)", replacement = "naturfag")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<elevernes\\>)", replacement = "elever")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<eleverne\\>)", replacement = "elever")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<undervisningen\\>)", replacement = "undervisning")

alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<adskiller\\>|\\<adskilte\\>)", replacement = "adskilles")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<ændre\\>|\\<ændrede\\>|\\<ændreforbedre\\>|\\<ændrer\\>)", replacement = "ændres")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afdække\\>|\\<afdækkede\\>|\\<afdækket\\>|\\<afdækkes\\>)", replacement = "afdækkes")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afgangsprøver\\>)", replacement = "afgangsprøve")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afhænger\\>|\\<afhængig\\>)", replacement = "afhænge")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afprøve\\>|\\<afprøvede\\>)", replacement = "afprøves")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afprøvninger\\>)", replacement = "afprøvning")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afsat\\>)", replacement = "afsættes")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afsættet\\>)", replacement = "afsæt")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afsluttende\\>)", replacement = "afsluttes")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afspejler\\>)", replacement = "afspejles")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<agerer\\>)", replacement = "agere")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktionsforskningsprojekter\\>)", replacement = "aktionsforskningsprojekt")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktionsforskning\\>)", replacement = "aktionsforskningsprojekt")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktive\\>)", replacement = "aktiv")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktiverer\\>)", replacement = "aktiveres")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktiviteter\\>|\\<aktiviteterne\\>)", replacement = "aktivitet")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktivt\\>)", replacement = "aktiv")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktører\\>)", replacement = "aktør")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktuelle\\>|\\<aktueller\\>|\\<aktuelt\\>)", replacement = "aktuel")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<alderen\\>)", replacement = "alder")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<algoritmiske\\>)", replacement = "algoritmisk")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<allerstørst\\>)", replacement = "størst")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almene\\>|\\<alment\\>)", replacement = "almen")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almindelige\\>|\\<almindeligt\\>)", replacement = "almindelig")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almindelighed\\>)", replacement = "generelt")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<alternative\\>|\\<alternativer\\>)", replacement = "alternativ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<ambitionen\\>|\\<ambitiøse\\>)", replacement = "ambition")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<andres\\>|)", replacement = "andre")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<anerkender\\>|\\<anerkendt\\>)", replacement = "anerkendes")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<angående\\>|\\<angår\\>)", replacement = "angå")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<angelsaksiske\\>|)", replacement = "angelsaksisk")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<ansvarlig\\>|\\<ansvarlighed\\>)", replacement = "ansvar")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<anvendeligheden\\>|\\<anvendelsen\\>)", replacement = "anvendelse")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<anvender\\>|\\<anvendes\\>|\\<anvendte\\>)", replacement = "anvende")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<anvender\\>|\\<anvendes\\>|\\<anvendte\\>)", replacement = "anvende")

####Sammenlægninger####
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<naturvidenskabens abc\\>)", replacement = "naturvidenskabens_abc")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<abcen\\>)", replacement = "naturvidenskabens_abc")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almen naturfaglig dannelse\\>)", replacement = "naturfaglig almendannelse")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<multiple choice\\>)", replacement = "multiplechoice")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktiviteterværksteder\\>)", replacement = "aktivitet værksted")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktivitetsafvikling\\>)", replacement = "aktivitet afvikling")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktivitetsbeskrivelser\\>)", replacement = "aktivitet beskrivelse")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almendannelse\\>)", replacement = "almen dannelse")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<almendannende\\>)", replacement = "almen dannende")


####Opslitninger####
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afdesign\\>)", replacement = "af design")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<afdet\\>)", replacement = "af det")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktionslæringlektionsstudier\\>)", replacement = "aktionslæring lektionsstudie")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktionslæringlektionsstudier\\>)", replacement = "aktionslæring lektionsstudie")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<aktionslæringlektionsstudier\\>)", replacement = "aktionslæring lektionsstudie")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<anvendelses\\>|\\<anvendelsesorienterede\\>|\\<anvendelsesorienteret\\>|\\<anvendelsesorientering\\>)", replacement = "orientering anvendelse")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<apparateropstillingerfysiske\\>)", replacement = "apparater opstilling fysisk")


###Fjerner her overflødige tal####
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<03\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<06\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<10\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<20\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1020\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<12\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<13\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<14\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1500\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1743\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<200\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<18\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<19\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1997\\>|\\<1998\\>|\\<1999\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2000\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2001\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2002\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2001\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2002\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2003\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2004\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2005\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2006\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2008\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2009\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<201\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2011\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2012\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2013\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2014\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2015\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2015a\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2015b\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2016\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2017\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2018\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<20182019\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<20183\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2019\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2020\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<2021\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<20212\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<23\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<25\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<27\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<3\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<30\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<35\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<37\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<4\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<40\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<43\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<49\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<56\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<612\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<64\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<65\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<67\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<7\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<70\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<78\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<22\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<1\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<85\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<86\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<88\\>)", replacement = " ")
alleSvar <- tm_map(alleSvar, content_transformer(gsub), pattern = "(\\<29660351\\>)", replacement = " ")


